### ISSUE TITLE
error when running r2z (AttributeError: 'numpy.ndarray' object has no attribute 'in_units_of')

### ISSUE THREAD

**Issue by fernan** [wutobias/r2z#1]
Hi Tobias, thanks for this package. I am new to this and just testing to see if I can get it to work with psi4. My initial attempt was using a google colab notebook (see attached notebook to reproduce the issue, this is essentially your zmatrix-demo notebook with very minimal tweaks). 

Because r2z is not available as a python package to install using pip or conda, I just copied all functions in zmatrix.py and z_helpers.py into a cell. Running this cell before running code from the examples provides access to these functions. No need to then run the specific imports as in the zmatrix-demo.ipynb examples.

This is the code from the examples I am running: 
```
from rdkit import Chem
from rdkit.Chem import AllChem
from simtk import unit
import numpy as np
import glob

from rdkit.Chem.Draw import IPythonConsole

rdmol = Chem.MolFromSmiles("CCOCC")
rdmol = AllChem.AddHs(rdmol)
setLabels(rdmol)
rdmol.Compute2DCoords()
rdmol

zm = ZMatrix(rdmol)
print(zm.z) # works OK!

AllChem.EmbedMolecule(rdmol)
AllChem.MMFFOptimizeMolecule(rdmol)
cart_crds = np.array(rdmol.GetConformers()[0].GetPositions())*unit.angstrom
print(cart_crds) # works OK!

z_crds = zm.build_z_crds(cart_crds) # FAILS!
print(z_crds) 

z_string  = zm.build_pretty_zcrds(cart_crds) # FAILS!
print(z_string)

```

And this is the errors I'm getting when attempting to call `build_z_crds()` or `build_pretty_zcrds()`: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-14-05b22af86ed5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 z_crds = zm.build_z_crds(cart_crds)
      2 print(z_crds)

[<ipython-input-9-c12dad6e5d86>](https://localhost:8080/#) in build_z_crds(self, crds)
    435             z_crds_dict[z_idx] = list()
    436             if z_idx == 0:
--> 437                 z_crds_dict[z_idx].append(crds[atm_idxs[0]].in_units_of(unit.nanometer))
    438             if z_idx > 0:
    439                 dist = pts_to_bond(crds[atm_idxs[0]],

AttributeError: 'numpy.ndarray' object has no attribute 'in_units_of'


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-d3110345b62c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 z_string  = zm.build_pretty_zcrds(cart_crds)
      2 print(z_string)


[<ipython-input-2-35efd1e7df81>](https://localhost:8080/#) in build_pretty_zcrds(self, crds)
    379     def build_pretty_zcrds(self, crds):
    380 
--> 381         z_crds_dict = self.build_z_crds(crds)
    382         z_string    = []
    383         for z_idx, atm_idxs in self.z.items():

[<ipython-input-2-35efd1e7df81>](https://localhost:8080/#) in build_z_crds(self, crds)
    401             z_crds_dict[z_idx] = list()
    402             if z_idx == 0:
--> 403                 z_crds_dict[z_idx].append(crds[atm_idxs[0]].in_units_of(unit.nanometer))
    404             if z_idx > 0:
    405                 dist = pts_to_bond(crds[atm_idxs[0]],

AttributeError: 'numpy.ndarray' object has no attribute 'in_units_of'
```

There are also other errors of the same kind when calling `pts_to_bond()` in other cells. 

[zmatrix_demo_for_colab.zip](https://github.com/wutobias/r2z/files/11750178/zmatrix_demo_for_colab.zip)

[rsz_reproduce_issue.zip](https://github.com/wutobias/r2z/files/11750086/rsz_reproduce_issue.zip)

**Comment by wutobias** [comment]
Thanks for the detailed report Fernán! 

I suspect that my example used older versions of `numpy`, `rdkit` and `openmm.unit` with which the reported parts of the code were not failing. I'll look into it next week.

--Tobias

**Comment by wutobias** [comment]
I re-wrote the code so that it now uses the `pint` package for unit conversion and handling instead of `openmm.unit`. This should solve some of the issues with np.ndarray objects. Can you please try again and let me know if it works for you?
Also note that I made the package pip installable, just run `pip install .` after cloning the repo.

This (based on your example) works for me:

```
from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np
import glob

from r2z import ureg
from r2z.zmatrix import ZMatrix

from rdkit.Chem.Draw import IPythonConsole

rdmol = Chem.MolFromSmiles("CCOCC")
rdmol = AllChem.AddHs(rdmol)
rdmol.Compute2DCoords()
rdmol
```

```
zm = ZMatrix(rdmol)
zm.z
```

```
AllChem.EmbedMolecule(rdmol)
AllChem.MMFFOptimizeMolecule(rdmol)
cart_crds = np.array(rdmol.GetConformers()[0].GetPositions())*ureg.angstrom
cart_crds
```

```
z_crds = zm.build_z_crds(cart_crds)
z_crds
```

```
z_string  = zm.build_pretty_zcrds(cart_crds)
print(z_string)
```

CC  @Sulstice, just in case this is also relevant for you.

**Comment by fernan** [comment]
Thanks @wutobias 

works like a charm now! And now it's easier thanks to the pip install (works directly inside google colab through `!pip install git+https://github.com/wutobias/r2z.git` followed by the required imports. Best, -f

**Comment by wutobias** [comment]
Happy to here it works for you. Thanks again for the report!

**Comment by wutobias** [comment]
Issue resolved.
